name: 'AYX Server Sync'
description: |
  Sync a GitHub Repository with an Alteryx Server.
author: Jupiter Bakakeu <jupiter.bakakeu@gmail.com>, <jupiter.bakakeu@alteryx.com>
inputs:
  ayx-server-api-url: 
    required: true
    description: 'alteryx server rest api url'
    default: 'http://ec2-3-66-136-169.eu-central-1.compute.amazonaws.com/webapi/'
  ayx-server-client-id: 
    required: true
    description: 'alteryx server client ID'
    default: '8DA78CE09C0E5D1abf4927846637f9a02e196b8eff52b61f03246ad16ad2c81125ef4a80920db80'
  ayx-server-client-secret: 
    required: true
    description: 'alteryx server client secret'
    default: '1f675a0f8d2c572ddd02005a3396fe7e89706fe4a39e0d5f39cf9b6463aecec8'
  ayx-user-mail: 
    required: true
    description: 'alteryx user mail'
    default: 'jupiter.bakakeu@alteryx.com'
  folder-to-sync: 
    required: true
    description: 'path of the repository folder to sync'
outputs:
  conclusion:
    description: |
      Final conclusion of the created check run:
        - 'success' if no failed export happened
        - 'failure' if any failed export happened
  test-report-file:
    description: Generated export report
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: orange
  icon: check-square
